apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
  labels:
    app: example-app
  annotations:
spec:
  selector:
    matchLabels:
      app: example-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: <+pipeline.variables.image>
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - username:
          value: <+pipeline.variables.username>
        - name: ENV_NAME
          value: <+env.name>
        - name: ENV_TYPE
          value: <+env.type>
        - name: COUNTRY
          value: <+env.variables.country>
